# Generated by Django 5.2.7 on 2025-12-03 06:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager'), ('HR', 'HR'), ('ADMIN', 'Admin')], default='EMPLOYEE', help_text="User's role in the organization", max_length=20)),
                ('employee_id', models.CharField(blank=True, help_text='Unique employee identifier', max_length=20, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=15)),
                ('department', models.CharField(blank=True, help_text='Department the user belongs to', max_length=100)),
                ('hire_date', models.DateField(blank=True, help_text='Date when the employee was hired', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the user account is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, help_text="Employee's date of birth", null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], help_text='Gender identity', max_length=1)),
                ('marital_status', models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed'), ('O', 'Other')], help_text='Marital status', max_length=1)),
                ('nationality', models.CharField(blank=True, help_text='Nationality', max_length=50)),
                ('personal_email', models.EmailField(blank=True, help_text='Personal email address', max_length=254)),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Emergency contact person name', max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Emergency contact phone number', max_length=15)),
                ('emergency_contact_relationship', models.CharField(blank=True, help_text='Relationship with emergency contact', max_length=50)),
                ('address_line_1', models.CharField(blank=True, help_text='Address line 1', max_length=200)),
                ('address_line_2', models.CharField(blank=True, help_text='Address line 2', max_length=200)),
                ('city', models.CharField(blank=True, help_text='City', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State/Province', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20)),
                ('country', models.CharField(blank=True, help_text='Country', max_length=100)),
                ('designation', models.CharField(blank=True, help_text='Job title/designation', max_length=100)),
                ('date_of_joining', models.DateField(blank=True, help_text='Date when employee joined the organization', null=True)),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TERMINATED', 'Terminated'), ('ON_LEAVE', 'On Leave'), ('PROBATION', 'Probation')], default='ACTIVE', help_text='Current employment status', max_length=20)),
                ('work_location', models.CharField(blank=True, help_text='Primary work location', max_length=200)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Current salary (confidential)', max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='USD', help_text='Salary currency code', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the employee profile is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, help_text='Direct manager/supervisor', limit_choices_to={'role__name__in': ['MANAGER', 'HR', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_employees', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='Link to user account', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Profile',
                'verbose_name_plural': 'Employee Profiles',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
