# Generated by Django 5.2.8 on 2025-12-03 18:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_leave_project_attendance_projectmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='annual_leaves',
            field=models.IntegerField(default=20, help_text='Annual leave balance (in days)'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='compensatory_leaves',
            field=models.IntegerField(default=0, help_text='Compensatory leave balance (in days)'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='emergency_leaves',
            field=models.IntegerField(default=5, help_text='Emergency leave balance (in days)'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='maternity_leaves',
            field=models.IntegerField(default=90, help_text='Maternity leave balance (in days)'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='paternity_leaves',
            field=models.IntegerField(default=15, help_text='Paternity leave balance (in days)'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='sick_leaves',
            field=models.IntegerField(default=10, help_text='Sick leave balance (in days)'),
        ),
        migrations.AddField(
            model_name='leave',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if leave was rejected'),
        ),
        migrations.AddField(
            model_name='leave',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='User who approved/rejected this leave', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to=settings.AUTH_USER_MODEL),
        ),
    ]
