# Generated by Django 5.2.8 on 2025-12-03 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_timesheetentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='Month for which payslip is generated (1-12)')),
                ('year', models.IntegerField(help_text='Year for which payslip is generated')),
                ('basic', models.DecimalField(decimal_places=2, help_text='Basic salary amount', max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, default=0, help_text='House Rent Allowance', max_digits=10)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, help_text='Other allowances (transport, medical, etc.)', max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, help_text='Total deductions (tax, PF, insurance, etc.)', max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, help_text='Net salary after deductions', max_digits=10)),
                ('pay_date', models.DateField(blank=True, help_text='Date when salary was paid', null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When the payslip was generated')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the payslip was last updated')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, help_text='Overtime hours worked', max_digits=5)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, help_text='Overtime payment', max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, help_text='Bonus amount', max_digits=10)),
                ('income_tax', models.DecimalField(decimal_places=2, default=0, help_text='Income tax deduction', max_digits=10)),
                ('provident_fund', models.DecimalField(decimal_places=2, default=0, help_text='Provident Fund deduction', max_digits=10)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=0, help_text='Professional tax deduction', max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSED', 'Processed'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Payslip status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('employee', models.ForeignKey(help_text='Employee for whom the payslip is generated', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payslip',
                'verbose_name_plural': 'Payslips',
                'ordering': ['-year', '-month', 'employee__first_name'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
